spring.datasource.url: 'jdbc:mysql://localhost:3306/moneyTest'
spring.datasource.username: 'root'
spring.jpa.hibernate.ddl-auto: 'update'
#spring:
#  datasource:
#    url: 'jdbc:h2:mem:moneyDbTest'
#    username: ''
#    password: ''
#  jpa.hibernate.ddl-auto: update



